# Generated by Django 4.1.2 on 2022-10-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ManyToManyField(related_name='review_movies', to='reviews.review'),
        ),
    ]
